### ISSUE TITLE
Docs - OutRank as a Python library

### ISSUE THREAD

**Issue by SkBlaz** [outbrain/outrank#29]
No reason not to use the library as just another ML framework within e.g., Notebooks. Required todos here:
1. Add documentation related to this aspect
2. Add a few notebooks with walk-through(s)
3. Additional tests that cover this functionality

**Comment by mglowacki100** [comment]
Hi @SkBlaz,

I am genuinely excited about testing this out! Could you please let me know when I can have a look?

Thank you!
Marek

**Comment by SkBlaz** [comment]
@mglowacki100 I appear to have missed this notification :facepalm: , example lib use was added, it's first docs page btw.
